---
title: "Assessment"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: paper
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
The assessment on this module will take the form of research projects, where you will collect data as a group (many hands make light work etc.) but complete the analysis and write the paper alone.  We will take advantage of living in one of the most interesting and instantly recognisable accent areas of the country by having a strong focus on Tyneside English for the research projects.


Your mark on this module will primarily be determined by the following:

* Mid-module data collection report: 25%, due 21st March 2019 at 3pm. 1000 words. This should be connected to the final assignment.
* Final research project/assignment: 75%, due 16th May 2019 at 3pm. 3000 words. You have the option to work in pairs for this assignment, in which case the word limit will be 4,500.

Please choose from one of the research projects and assignments below.  Note that the lab projects involve data collection with a member of staff and your classmates, and thus require forward planning.  If you intend to complete one of these projects, register your interest by Sunday 3rd March at the following link:
https://goo.gl/forms/mRTag557d8si9Zum2


### Handing in your assignments
This module is electronic submission only.  You do not need to submit a paper copy of your assessment. Instead, you will use the TurnItIn submission box on [Blackboard](https://blackboard.ncl.ac.uk/).  TurnItIn opens a week prior to the hand-in date.

### Selecting a project
Please choose from one of the projects below and register your selection by Sunday 3rd March at the following link:
https://goo.gl/forms/mRTag557d8si9Zum2

Note that the lab projects require a potentially bigger commitment from you initially, in terms of turning up at the phonetics lab to record your recruited speakers.  These projects are arguably more ambitious, but are meant to give you a realistic experience of what it is like to conduct high quality research at a university.  Thus, you will be working alongside staff and PhD students in the recruitment and recording process.  Although this assessment is 100% marked on your individual contribution, you will be working as a team (with the assigned project manager) to design the experiment and collect data in the lab projects.

*SEE THE [READING](reading.html) TAB FOR FULL REFERENCES*

## Tyneside voiceless stops
**Project Lead: Danielle Turton**

In this project, you will recruit Tyneside speakers to take part in an ultrasound tongue imaging study, which simultaneously monitors acoustics and articulation of voiceless stops.  For your write-up, you will analyse speakers’ consonants either by auditory and acoustic analysis, or (advanced!) by ultrasound tongue imaging.


*Mid-module requirements*: Recruit Tyneside speakers, make recordings in lab, transcribe in DARLA, and complete write-up in line with mid-module instructions.


<BR>

## Tyneside vowel perception and production
**Project Lead: Jasmine Warburton**

What is the phonemic and phonetic status of pairs of vowels in Tyneside English today?  In this project, you will recruit local speakers to take part in a reading task, followed by a test of whether two words sound the same or different.  

*Mid-module requirements*: Recruit Tyneside speakers, make recordings in lab, transcribe in DARLA, and complete write-up in line with mid-module instructions.

*Jasmine's recommended reading on perception*: [click here](https://newcastle-my.sharepoint.com/:u:/g/personal/ndmt5_newcastle_ac_uk/EVe2UL3doB9Gs-fP3_9uTEwBI6H3GiL1aX_Yjk4uOZqLgg?e=BwKvbQ)

Additional suggestions for reading include anything on mergers and distinctions, or Tyneside vowels.

## Sociolinguistic masking noise
**Project Lead: Sophie Meekings**

Do people speak the same when they can’t hear the sound of their own voice?  In this project, you will recruit participants from the Tyneside area for a sociolinguistic masking noise map task.  You will analyse the results, testing whether speakers use more or less non-standard pronunciations when they cannot hear themselves speak.

*Mid-module requirements*: Recruit Tyneside speakers, make recordings in lab, transcribe in DARLA, and complete write-up in line with mid-module instructions.

Aside from the [Mahl(1972)](https://books.google.co.uk/books?hl=en&lr=&id=bfdFBQAAQBAJ&oi=fnd&pg=PA211&dq=mahl+1972%5D&ots=Skxq9p2aEi&sig=ojKmT-zLbqBiPzxecr0yEcQg03U#v=onepage&q&f=false) description given by Sophie in the lecture, your reading should mainly focus on your specific variable of choice.  This is a little-studied phenomenon so anything relevant you can find will be of interest, but don't expect to find much out there.


## Language change across the lifespan
**Individual project**

In this project, you will select a public figure and analyse their speech at two points in their life.  You transcribe and force-align the data using tools from class, and will select a phonological variable (or variables) to monitor potential change.  You will produce quantitative analysis of the findings.

*Mid-module requirements*: Decide on speaker, source and download appropriate sound files, transcribe in DARLA.

Your recommended reading with include your specific variable, and also studies of lifespan change and plasticity.s

## Illustrations of the IPA
**Individual project**

Record a representative number of speakers from a speech community of your choice to provide an acoustic description in the style of [Illustrations of the IPA](https://www.cambridge.org/core/journals/journal-of-the-international-phonetic-association/illustrations-of-the-ipa).  Alternatively, provide a more in-depth analysis of a particular variable with reference to relevant independent variables such as morphological class, adjacent sounds, or external factors such as age and social class.  Present your quantitative findings using the skills from class.

*Mid-module requirements*: Record speaker(s), transcribe in DARLA or Praat if appropriate, and prepare data for analysis stage.


## Individual research project: *PG only*
Design a project of your choosing, in agreement with the module leader.  