---
title: "Labs"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: paper
---

<link href="https://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css" rel="stylesheet">


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lab class: Check timetable for your session.

Lab classes are two hours, schedule is subject to change

N.B. For Praat classes you will need your headphones `r icon::fa("headphones")`!  Check table for when to bring headphones to class!  Note that some of the university computers have problems playing Praat through iphone headphones, so if you have others then you might want to bring them.

| Session |             Lab            |   Info  |
|:----:|:------------------------------:|:-------------------------:|
|   1  |          Excel 1: Intro, graphs and tables          |                       |
|   2  |          Praat 1: Intro, textgrids and vowels              | `r icon::fa("headphones")`   |
|   3  |          ELAN, DARLA and the Praat Handcoder           | `r icon::fa("headphones")` |
|   4  |          Vowels and NORM           |         |
|   5  |          Praat 2: consonants         | `r icon::fa("headphones")` |
|   6  |          Excel 2: Chi-square, correlation, cross-tab, stats      |         |


## Reading for lab classes
Chapter 8 of [Ladefoged and Johnson (2015)](https://libsearch.ncl.ac.uk/primo-explore/fulldisplay?docid=NCL_ALMA51104441400002411&context=L&vid=NEWUI&search_scope=NotPC&tab=default_tab&lang=en_US) is the recommended intro to acoustic phonetics and is available to online via the library.  For more in-depth reading try [Johnson (2012)](https://libsearch.ncl.ac.uk/primo-explore/fulldisplay?docid=NCL_ALMA2162877050002411&context=L&vid=NEWUI&search_scope=NotPC&isFrbr=true&tab=default_tab&lang=en_US) and [Ladefoged (1996)](https://libsearch.ncl.ac.uk/primo-explore/fulldisplay?docid=NCL_ALMA2158870380002411&context=L&vid=NEWUI&search_scope=NotPC&isFrbr=true&tab=default_tab&lang=en_US).  For a Sociophonetics slant try [Thomas (2011)](https://libsearch.ncl.ac.uk/primo-explore/fulldisplay?docid=NCL_ALMA2162924950002411&context=L&vid=NEWUI&search_scope=NotPC&tab=default_tab&lang=en_US).


## R classes
Recommended for postgrads - module HSS8005 weeks 8 and 9, Tues and Thurs 2-4pm


